name: "Install Nomos Dependencies"

inputs:
  github_token:
    description: "The GitHub token to use for rate limiting."
    required: true
  os:
    description: "The operating system to install dependencies for."
    required: true
  target_triple:
    description: "The target triple to install dependencies for."
    required: true

description: "Install Risc0 toolchain. Requires the Rust toolchain to be installed."

runs:
  using: "composite"
  steps:
    - name: Install risc0
      uses: ./.github/actions/install-risc0
      with:
        github_token: ${{ inputs.github_token }}
        os: ${{ inputs.os }}
        target_triple: ${{ inputs.target_triple }}

    - name: Setup system
      if: inputs.os == 'linux'
      shell: bash
      run: |
        sudo apt-get update

    - name: Setup i686-linux compilation
      if: inputs.target_triple == 'i686-unknown-linux-gnu'
      shell: bash
      run: |
        # Add i686 target
        rustup target add i686-unknown-linux-gnu

        # Add i686 architecture 
        sudo dpkg --add-architecture i386
        sudo apt-get update
        
        # Install (exclusive) i686 dependencies
        sudo apt-get install -yq libssl-dev:i386 gcc-multilib g++-multilib
        
        # Configure libssl for i686
        echo "OPENSSL_LIB_DIR=/usr/lib/i386-linux-gnu" >> $GITHUB_ENV
        echo "OPENSSL_INCLUDE_DIR=/usr/include/openssl" >> $GITHUB_ENV

    - name: Setup x86_64-linux compilation
      if: inputs.target_triple == 'x86_64-unknown-linux-gnu'
      shell: bash
      run: |
        sudo apt-get install -yq openssl libssl-dev

    - name: Install Linux dependencies
      if: inputs.os == 'linux'
      shell: bash
      run: |
        # Librocksdb dependencies
        sudo apt-get install -yq clang

        # Tauri dependencies
        ## Tools
        sudo apt-get install -yq \
          build-essential \
          curl \
          wget \
          file
        
        ## Libs
        sudo apt-get install -yq \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev

        ### Workaround for original dependency `libwebkit2gtk-4.0-dev`
        sudo apt-get install -yq libwebkit2gtk-4.1-dev
        sudo ln -sf /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.1.so.0 /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37
        sudo ln -sf /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.1.so.0 /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so.18
