[package]
edition = "2021"
license = { workspace = true }
name = "nomos-time"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
cryptarchia-engine = { workspace = true, features = ["serde", "tokio"] }
futures = "0.3"
log = "0.4.22"
overwatch = { workspace = true }
serde = { version = "1.0", optional = true, features = ["derive"] }
services-utils = { workspace = true }
sntpc = { version = "0.5", optional = true, features = ["tokio-socket"] }
thiserror = { version = "2.0", optional = true }
time = "0.3"
tokio = { version = "1", features = ["macros", "sync"] }
tokio-stream = "0.1"
nomos-utils = { workspace = true, features = ["time"], optional = true }
serde_with = { version = "3.12", optional = true }

[features]
ntp = ["dep:sntpc", "dep:thiserror"]
serde = ["dep:serde"]
time = ["serde", "dep:nomos-utils", "dep:serde_with"]
