global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "Monitoring"

scrape_configs:
  - job_name: "Nomos nodes"
    static_configs:
    - targets:
      - bootstrap:8080
      - libp2p-node-1:8080
      - libp2p-node-2:8080
      - libp2p-node-3:8080
