use std::{
    collections::{BTreeMap, HashSet},
    panic,
};

use consensus_engine::{Block, LeaderProof, Qc, StandardQc, View};
use proptest::prelude::*;
use proptest::test_runner::Config;
use proptest_state_machine::{prop_state_machine, ReferenceStateMachine, StateMachineTest};
use system_under_test::ConsensusEngineTest;

prop_state_machine! {
    #![proptest_config(Config {
        // Only run 100 cases by default to avoid running out of system resources
        // and taking too long to finish.
        cases: 100,
        .. Config::default()
    })]

    #[test]
    // run 50 state transitions per test case
    fn happy_path(sequential 1..50 => ConsensusEngineTest);
}

// A reference state machine, which is used to generate state transitions
// and can also be compared against the consensus-engine state mutated by transitions.
// In other words, this is the expected state as a result of each state transition generated by fuzzing.
// We should try to design this reference state as simple/intuitive as possible,
// so that we don't need to replicate the logic implemented in consensus-engine.
#[derive(Clone, Debug)]
pub struct RefState {
    chain: BTreeMap<View, HashSet<Block>>,
    highest_voted_view: View,
}

// State transtitions that will be picked randomly
#[derive(Clone, Debug)]
pub enum Transition {
    ReceiveBlock(Block, bool),
    ApproveBlock(Block, bool),
    //TODO: add more transitions
    //TODO: consider invalid transitions that must be rejected by consensus-engine
}

const LEADER_PROOF: LeaderProof = LeaderProof::LeaderId { leader_id: [0; 32] };

impl ReferenceStateMachine for RefState {
    type State = Self;

    type Transition = Transition;

    // Initialize the reference state machine
    fn init_state() -> BoxedStrategy<Self::State> {
        let genesis_block = Block {
            view: 0,
            id: [0; 32],
            parent_qc: Qc::Standard(StandardQc::genesis()),
            leader_proof: LEADER_PROOF.clone(),
        };

        Just(RefState {
            chain: BTreeMap::from([(genesis_block.view, HashSet::from([genesis_block.clone()]))]),
            highest_voted_view: -1,
        })
        .boxed()
    }

    // Generate transitions based on the current reference state machine
    fn transitions(state: &Self::State) -> BoxedStrategy<Self::Transition> {
        prop_oneof![
            3 => state.transition_receive_block(),
            2 => state.transition_approve_block(),
        ]
        .boxed()
    }

    // Check if the transition is valid for a given reference state, before applying the transition
    // If invalid, the transition will be ignored and a new transition will be generated.
    fn preconditions(_state: &Self::State, transition: &Self::Transition) -> bool {
        match transition {
            Transition::ReceiveBlock(_, _) => true,
            Transition::ApproveBlock(_, _) => true,
        }
    }

    // Apply the given transition on the reference state machine,
    // so that it can be used to generate next transitions and be compared against the real state.
    fn apply(mut state: Self::State, transition: &Self::Transition) -> Self::State {
        match transition {
            Transition::ReceiveBlock(block, is_safe) => {
                if *is_safe {
                    state
                        .chain
                        .entry(block.view)
                        .or_default()
                        .insert(block.clone());
                }
            }
            Transition::ApproveBlock(block, is_approvable) => {
                if *is_approvable {
                    state.highest_voted_view = block.view;
                }
            }
        }

        state
    }
}

impl RefState {
    // Generate a Transition::ReceiveBlock.
    fn transition_receive_block(
        &self,
    ) -> proptest::strategy::Map<proptest::sample::Select<Block>, impl Fn(Block) -> Transition>
    {
        let blocks = self
            .chain
            .iter()
            .rev()
            .take(5)
            .flat_map(|(_view, blocks)| blocks.iter().cloned())
            .collect::<Vec<Block>>();
        let (last_view, _) = self.chain.last_key_value().unwrap();
        let last_view = last_view.clone();

        proptest::sample::select(blocks).prop_map(move |parent| -> Transition {
            let block = Self::consecutive_block(&parent);
            let is_safe = block.view >= last_view;
            Transition::ReceiveBlock(block, is_safe)
        })
    }

    // Generate a Transition::ApproveBlock.
    fn transition_approve_block(
        &self,
    ) -> proptest::strategy::Map<proptest::sample::Select<Block>, impl Fn(Block) -> Transition>
    {
        let blocks = self
            .chain
            .iter()
            .rev()
            .take(5)
            .flat_map(|(_view, blocks)| blocks.iter().cloned())
            .collect::<Vec<Block>>();
        let highest_voted_view = self.highest_voted_view.clone();

        proptest::sample::select(blocks).prop_map(move |block| {
            let is_approvable = block.view > highest_voted_view;
            Transition::ApproveBlock(block, is_approvable)
        })
    }

    fn consecutive_block(parent: &Block) -> Block {
        Block {
            // use rand because we don't want this to be shrinked by proptest
            id: rand::thread_rng().gen(),
            view: parent.view + 1,
            parent_qc: Qc::Standard(StandardQc {
                view: parent.view,
                id: parent.id,
            }),
            leader_proof: LEADER_PROOF.clone(),
        }
    }
}

// StateMachineTest defines how transitions are applied to the real state machine
// and what checks should be performed.
impl StateMachineTest for ConsensusEngineTest {
    // SUT is the real state machine that we want to test.
    type SystemUnderTest = Self;

    // A reference state machine that should be compared against the SUT.
    type Reference = RefState;

    // Initialize the SUT state
    fn init_test(
        _ref_state: &<Self::Reference as proptest_state_machine::ReferenceStateMachine>::State,
    ) -> Self::SystemUnderTest {
        ConsensusEngineTest::new()
    }

    // Apply the transition on the SUT state and check post-conditions
    fn apply(
        state: Self::SystemUnderTest,
        _ref_state: &<Self::Reference as proptest_state_machine::ReferenceStateMachine>::State,
        transition: <Self::Reference as proptest_state_machine::ReferenceStateMachine>::Transition,
    ) -> Self::SystemUnderTest {
        println!("{transition:?}");

        match transition {
            Transition::ReceiveBlock(block, is_safe) => {
                let result = panic::catch_unwind(|| state.engine.receive_block(block.clone()));
                if is_safe {
                    assert!(result.is_ok());
                    let result = result.unwrap();
                    assert!(result.is_ok());
                    let engine = result.unwrap();
                    assert!(engine.blocks_in_view(block.view).contains(&block));

                    ConsensusEngineTest { engine }
                } else {
                    assert!(result.is_err() || result.unwrap().is_err());

                    state
                }
            }
            Transition::ApproveBlock(block, is_approvable) => {
                let result = panic::catch_unwind(|| state.engine.approve_block(block.clone()));
                if is_approvable {
                    assert!(result.is_ok());
                    let (engine, _send) = result.unwrap();
                    //TODO: assert 'send'
                    assert_eq!(engine.highest_voted_view(), block.view);

                    ConsensusEngineTest { engine }
                } else {
                    assert!(result.is_err());

                    state
                }
            }
        }
    }

    // Check invariants after every transition
    fn check_invariants(
        state: &Self::SystemUnderTest,
        ref_state: &<Self::Reference as ReferenceStateMachine>::State,
    ) {
        let (last_view, _) = ref_state.chain.last_key_value().unwrap();
        //TODO: this may be false in unhappy path
        assert_eq!(state.engine.current_view(), last_view.clone());

        assert_eq!(
            state.engine.highest_voted_view(),
            ref_state.highest_voted_view
        );

        //TODO: add more invariants with more public functions of Carnot
    }
}

// SUT is a system (state) that we want to test.
mod system_under_test {
    use consensus_engine::{
        overlay::{FlatOverlay, RoundRobin, Settings},
        *,
    };

    use crate::LEADER_PROOF;

    #[derive(Clone, Debug)]
    pub struct ConsensusEngineTest {
        pub engine: Carnot<FlatOverlay<RoundRobin>>,
    }

    impl ConsensusEngineTest {
        pub fn new() -> Self {
            let engine = Carnot::from_genesis(
                [0; 32],
                Block {
                    view: 0,
                    id: [0; 32],
                    parent_qc: Qc::Standard(StandardQc::genesis()),
                    leader_proof: LEADER_PROOF.clone(),
                },
                FlatOverlay::new(Settings {
                    nodes: vec![[0; 32]],
                    leader: RoundRobin::default(),
                }),
            );

            ConsensusEngineTest { engine }
        }
    }
}
