[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-executor"
version = "0.1.0"

[dependencies]
async-trait              = "0.1"
axum                     = { version = "0.6" }
clap                     = { version = "4.5.13", features = ["derive"] }
color-eyre               = "0.6.0"
hyper                    = { version = "0.14", features = ["full"] }
kzgrs-backend            = { workspace = true }
nomos-api                = { workspace = true }
nomos-blend-service      = { workspace = true, features = ["libp2p"] }
nomos-core               = { workspace = true }
nomos-da-dispersal       = { workspace = true }
nomos-da-network-core    = { workspace = true }
nomos-da-network-service = { workspace = true }
nomos-da-sampling        = { workspace = true, features = ["rocksdb-backend"] }
nomos-da-verifier        = { workspace = true, features = ["libp2p", "rocksdb-backend"] }
nomos-libp2p             = { workspace = true }
nomos-mempool            = { workspace = true, features = ["libp2p", "mock"] }
nomos-network            = { workspace = true, features = ["libp2p"] }
nomos-node               = { workspace = true }
nomos-storage            = { workspace = true, features = ["rocksdb"] }
overwatch-derive         = { workspace = true }
overwatch-rs             = { workspace = true }
rand                     = "0.8"
rand_chacha              = "0.3"
serde                    = { version = "1", features = ["derive"] }
serde_yaml               = "0.9"
subnetworks-assignations = { workspace = true }
tower-http               = { version = "0.4", features = ["cors", "trace"] }
tracing                  = "0.1.40"
utoipa                   = "4.0"
utoipa-swagger-ui        = { version = "4.0" }
uuid                     = { version = "1.10.0", features = ["v4"] }

[features]
default         = ["tracing"]
instrumentation = ["nomos-node/instrumentation"]
tracing         = ["nomos-node/tracing"]
